services:
  elasticmq:
    image: softwaremill/elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:9324 | grep -q ''"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elasticmq-net

  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - elasticmq
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    entrypoint: >
      sh -c "
      aws --region=us-west-2 --endpoint=http://elasticmq:9324 sqs create-queue --queue-name=dev &&
      aws --region=us-west-2 --endpoint=http://elasticmq:9324 sqs create-queue --queue-name=error
      "
    networks:
      - elasticmq-net
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=some_pass
      - POSTGRES_DB=dev
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    ports:
      - "5050:80"
    networks:
      - postgres-network
    depends_on:
      - postgres
networks:
  elasticmq-net:
    driver: bridge
  postgres-network:
    driver: bridge