CREATE TABLE "customers" (
                             "customer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "persona_id" varchar(250) NOT NULL UNIQUE
);

CREATE TABLE "orders" (
                          "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "customer_id" INT NOT NULL,
                          "quantity" INT NOT NULL,
                          "status_id" INT NOT NULL DEFAULT 1,
                          "total_cost" int NOT NULL
);

CREATE TABLE "status" (
                          "status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "status_name" varchar(30)
);

CREATE TABLE "products" (
                            "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "price" INT NOT NULL,
                            "VAT" INT NOT NULL
);

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("status_id") REFERENCES "status" ("status_id");

INSERT INTO "status" ("status_name") VALUES
                                         ('placed'),
                                         ('pending'),
                                         ('approved'),
                                         ('denied'),
                                         ('cancelled'),
                                         ('collected');

INSERT INTO "products" ("price", "VAT") VALUES
                                         (100, 15);


INSERT INTO "customers" ("persona_id") VALUES
                                                        ('124332'),
                                                        ('213213'),
                                                        ('21321');


CREATE TABLE stocks (
                        stock_id SERIAL PRIMARY KEY,
                        stock_data JSONB
);

INSERT INTO "stocks" ("stock_data") VALUES ('{}')