CREATE TABLE "customers" (
                             "customer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "name" varchar(120) NOT NULL,
                             "banking_details" varchar(250) NOT NULL
);

CREATE TABLE "orders" (
                          "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "customer_id" INT NOT NULL,
                          "quantity" INT NOT NULL,
                          "status_id" INT NOT NULL DEFAULT 1,
                          "total_cost" int NOT NULL,
                          "reference_number" varchar(50) NOT NULL
);

CREATE TABLE "status" (
                          "status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "status_name" varchar(30)
);

CREATE TABLE "products" (
                            "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "price" INT NOT NULL,
                            "VAT" INT NOT NULL
);

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("status_id") REFERENCES "status" ("status_id");

INSERT INTO "status" ("status_name") VALUES
                                         ('placed'),
                                         ('approved'),
                                         ('denied'),
                                         ('cancelled'),
                                         ('collected');

INSERT INTO "products" ("price", "VAT") VALUES
                                         (100, 15);


INSERT INTO "customers" ("name", "banking_details") VALUES
                                                        ('John Doe', 'Bank of XYZ, Account Number: 1234567890'),
                                                        ('Jane Smith', 'Bank of ABC, Account Number: 0987654321'),
                                                        ('Alice Johnson', 'Bank of PQR, Account Number: 1122334455');
